### ISSUE TITLE
GitHub Actionsのbundle installの実行結果をキャッシュできるようにする

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/payment_app#21]
## このIssueについて

https://blog.freks.jp/github-action-cache/

上記記事の以下を参考にGitHub Actionsのbundle installの実行結果をキャッシュできるようにする
```yml
    steps:
      - uses: actions/checkout@v1
      - name: Cache bundle directory
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Prepare bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
```
